import "styles/globals.css";

import {Vazirmatn} from 'next/font/google'
import {MainLayout} from "components/MainLayout";
import PrelineScript from "components/PrelineScript";
import {ReduxProvider} from "store/provider";
import {dir, locales} from "../../helpers";
import localFont from "next/font/local";
import {getLang} from "./dictionary";

// import localFont from 'next/font/local'
//
// const localFont = localFont({
//     src: [
//         {
//             path: './fonts/VazirMatn-Bold-FD.ttf',
//             weight: 'bold',
//             style: 'italic',
//         }
//     ],
//     fontFamily: 'VazirMatn',
//     display: 'swap',
// })

// const vazirmatn = Vazirmatn({
//     subsets: [
//         'arabic',
//         'latin',
//     ],
//     display: 'swap',
// })

const vazirmatn = localFont({
    src: "../../assets/Vazir.woff2",
    display: "swap",
});


export async function generateStaticParams() {
    return locales.map((locale) => ({
        lang: locale,
        dir: dir[locale]
    }))
}

export const metadata = {
    title: {
        default: "تاپ ریت",
        template: "%s | تاپ ریت",
    },
    description: "Generated by create next app",
};

export default async function RootLayout({children, params}) {
    const lang = (await params).lang
    const dictionary = await getLang(lang);
    const dir = lang === 'en-US' ? 'ltr' : 'rtl'
    return (
        <html lang={lang} dir={dir}>
        <body className={vazirmatn.className}>
        <ReduxProvider>
            <MainLayout lang={lang} dictionary={dictionary}>
                {children}
            </MainLayout>
        </ReduxProvider>
        </body>
        <PrelineScript/>
        </html>
    );
}
