import "@/app/globals.css";

export const metadata = {
    title: {
        default: "آیتم",
        template: "%s | آیتم",
    },
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="fa-IR" dir="rtl">
        <body>
        {children}
        </body>
        </html>
    );
}
